apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sbms-app
  name: sbms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbms-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sbms-app
    spec:
      containers:
      - image: docker.io/hamvasaron/sbms:0.0.1-SNAPSHOT
        name: sbms
        resources: {}
status: {}
